name: BDD Tests

on:
    push:
        branches:
        - master
        paths-ignore:
        - 'README.md'
        - '.vscode/**'
        - '**.md'
    pull_request:
        branches:
            - master
        paths-ignore:
        - 'README.md'
        - '.vscode/**'
        - '**.md'

jobs:
  bdd:
    runs-on: ubuntu-latest
    container: rofrano/pipeline-selenium:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            python -m pip install -U pip poetry
            poetry config virtualenvs.create false
            poetry add psycopg2-binary
            poetry install

      - name: Run the service locally
        run: |
                echo "\n*** STARTING APPLICATION ***\n"
                gunicorn --log-level=info --bind=0.0.0.0:8080 wsgi:app &
                echo "Waiting for service to stabilize..."
                sleep 5
                echo "Checking service /health..."
                curl -i http://localhost:8080/health
                echo "\n*** SERVER IS RUNNING ***"
        env:
            DATABASE_URI: postgresql://postgres:pgs3cr3t@postgres:5432/postgres

      - name: Run Integration Tests
        run: behave