name: BDD Tests

on:
    push:
        branches:
        - master
        paths-ignore:
        - 'README.md'
        - '.vscode/**'
        - '**.md'
    pull_request:
        branches:
            - master
        paths-ignore:
        - 'README.md'
        - '.vscode/**'
        - '**.md'

jobs:
  bdd:
    runs-on: ubuntu-latest
    container: rofrano/pipeline-selenium:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            python -m pip install -U pip poetry
            poetry config virtualenvs.create false
            poetry install

      - name: Run Integration Tests
        run: behave